apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-db
  template:
    metadata:
      labels:
        app: paymybuddy-db
    spec:
      containers:
        - name: paymybuddy-db
          image: k1nra/paymybuddy-db
          envFrom:
            - secretRef:
                name: paymybuddy-secret
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-db
spec:
  selector:
    app: paymybuddy-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

