apiVersion: v1
kind: Secret
metadata:
  name: paymybuddy-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: dXNlcg==  # "user" en base64
  SPRING_DATASOURCE_PASSWORD: cGFzc3dvcmQ=  # "password" en base64

